import { create } from "zustand";
import { persist } from "zustand/middleware";
import { images } from "@/assets/assets";

const initialProducts = [
  {
    id: "PRD-JS001",
    title: "Spicy Plantain Chips",
    description: "Experience the perfect harmony of sweet and heat. Our plantain chips are hand-sliced from premium, sun-ripened plantains and kettle-fried to a signature crunch. Each batch is dusted with a bespoke blend of local chili peppers and a hint of sea salt for an addictive flavor profile that defines the Joy Snacky experience. Available in Min Pack, Super Pack, Family Pack, and Party Time sizes.",
    price: 20.0,
    category: "Snacks",
    rating: 4.8,
    availability: true,
    state: "New",
    type: "Product",
    images: [images.chips],
    weight: "Min Pack",
    variants: [
      { label: "Min Pack", price: 20.0 },
      { label: "Super Pack", price: 50.0 },
      { label: "Family Pack", price: 100.0 },
      { label: "Party Time", price: 150.0 },
    ],
    ingredients: "Sun-ripened plantains, vegetable oil, local chili powder, sea salt.",
    nutritionInfo: "Calories: 160 per serving, Fat: 9g, Sodium: 110mg",
    shelfLife: "3 weeks (sealed)",
    allergens: "None",
    storage: "Store in a cool, dry place. Reseal after opening to maintain crunch.",
    reviews: [
      { reviewerName: "Kojo M.", rating: 5, comment: "The best plantain chips on campus! Perfect spice level." },
      { reviewerName: "Ama R.", rating: 4, comment: "Crispy and fresh. Maybe a bit too spicy for some, but I love it!" }
    ],
  },
  {
    id: "PRD-JS002",
    title: "Chicken Spring Rolls",
    description: "A delicate, golden-crisp shell gives way to a succulent filling of tender shredded chicken breast, finely julienned vegetables, and a secret infusion of ginger and sesame. These spring rolls are prepared fresh daily, offering a light yet deeply satisfying gourmet snack that's perfect for a quick bite between lectures. Available in packs of 6, 12, or 40 pieces.",
    price: 18.0,
    category: "Appetizers",
    rating: 4.9,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.springRolls],
    weight: "6 pieces",
    variants: [
      { label: "6 pieces", price: 18.0 },
      { label: "12 pieces", price: 31.0 },
      { label: "40 pieces", price: 100.0 },
    ],
    ingredients: "Chicken breast, wheat wrapper, cabbage, carrots, spring onions, ginger, sesame oil, soy sauce.",
    nutritionInfo: "Protein: 12g, Calories: 240 per serving",
    shelfLife: "2 days (refrigerated)",
    allergens: "Contains Wheat (Gluten), Soy, Sesame.",
    storage: "Best served warm. Reheat in an oven or air fryer for 3 minutes at 180°C for maximum crispness.",
    reviews: [
      { reviewerName: "Nana Y.", rating: 5, comment: "So crispy and the chicken is seasoned perfectly." }
    ],
  },
  {
    id: "PRD-JS003",
    title: "Vegetable Samosas",
    description: "Our triangular parcels of joy feature a thin, crispy pastry enveloping a vibrant heart of spiced garden peas, diced potatoes, and aromatic herbs. Each bite is a journey through authentic spices, carefully balanced to provide a savory punch without being overwhelming. A vegetarian favorite available in packs of 5, 10, or 40 pieces.",
    price: 20.0,
    category: "Appetizers",
    rating: 4.7,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.samosas],
    weight: "5 pieces",
    variants: [
      { label: "5 pieces", price: 20.0 },
      { label: "10 pieces", price: 35.0 },
      { label: "40 pieces", price: 135.0 },
    ],
    ingredients: "Wheat flour, potatoes, green peas, onions, cumin, turmeric, coriander, garam masala.",
    nutritionInfo: "Calories: 180 per piece, Vegan Friendly",
    shelfLife: "2 days (refrigerated)",
    allergens: "Contains Wheat (Gluten).",
    storage: "Keep refrigerated. For best results, air fry for 5 minutes at 160°C.",
    reviews: [
      { reviewerName: "Ekow B.", rating: 4, comment: "Excellent seasoning. Goes great with the dip." }
    ],
  },
  {
    id: "PRD-JS004",
    title: "Gourmet Meat Pies",
    description: "A true campus classic. Our Beef Meat Pies feature a meticulously crafted buttery, flaky pastry shell that melts in your mouth. Inside, you'll find a hearty and savory filling of premium seasoned minced beef, tender potatoes, and garden-fresh carrots, all simmered in a rich gravy. Available in packs of 10, 15, or 40 pieces.",
    price: 50.0,
    category: "Pastries",
    rating: 4.6,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.meatPie],
    weight: "10 pieces",
    variants: [
      { label: "10 pieces", price: 50.0 },
      { label: "15 pieces", price: 80.0 },
      { label: "40 pieces", price: 190.0 },
    ],
    ingredients: "Wheat flour, butter, minced beef, potatoes, carrots, onions, beef stock, spices.",
    nutritionInfo: "Protein: 8g, Calories: 320",
    shelfLife: "2 days (refrigerated)",
    allergens: "Contains Wheat (Gluten), Milk (Butter).",
    storage: "Best served warm. Refrigerate if not consumed within 4 hours.",
    reviews: [
      { reviewerName: "Abena K.", rating: 4, comment: "The pastry is so flaky!" }
    ],
  },
  {
    id: "PRD-JS005",
    title: "Caramel Popcorn",
    description: "Air-popped to perfection and coated in our secret, small-batch rich caramel sauce. A sweet and salty legend.",
    price: 15.0,
    category: "Snacks",
    rating: 4.9,
    availability: true,
    state: "New",
    type: "Product",
    images: [images.img1],
    weight: "250g",
    ingredients: "Corn kernels, brown sugar, butter, sea salt, vanilla extract.",
    nutritionInfo: "Calories: 120 per cup, Fat: 5g, Sugar: 12g",
    shelfLife: "3 weeks",
    allergens: "Contains Milk (Butter).",
    storage: "Store in a cool, dry place. Reseal tightly.",
    reviews: [
      { reviewerName: "Ama R.", rating: 5, comment: "Best popcorn on campus!" }
    ],
  },
  {
    id: "PRD-JS006",
    title: "Sausage Rolls",
    description: "Golden, flaky pastry wrapped around a juicy, well-seasoned sausage filling. A Joy Snacky staple that pairs perfectly with any of our drinks. Available in packs of 10, 15, or 40 pieces — great for sharing at events or stocking up.",
    price: 50.0,
    category: "Pastries",
    rating: 4.7,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.img1],
    weight: "10 pieces",
    variants: [
      { label: "10 pieces", price: 50.0 },
      { label: "15 pieces", price: 80.0 },
      { label: "40 pieces", price: 190.0 },
    ],
    ingredients: "Wheat flour, butter, sausage meat, onions, mixed herbs, egg wash.",
    nutritionInfo: "Protein: 7g, Calories: 280 per piece",
    shelfLife: "2 days (refrigerated)",
    allergens: "Contains Wheat (Gluten), Milk (Butter), Egg.",
    storage: "Best served warm. Reheat in an oven or air fryer for 5 minutes at 180°C.",
    reviews: [],
  },
  {
    id: "PRD-JS007",
    title: "Sobolo Juice",
    description: "A refreshing, deep-red hibiscus drink bursting with a tart, fruity flavor. Made from dried hibiscus petals blended with natural spices, our Sobolo is a campus favorite that quenches your thirst and revitalizes your senses. Available in 250ml, 1.5lt, and 5lt sizes.",
    price: 4.0,
    category: "Drinks",
    rating: 4.8,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.img1],
    weight: "250ml",
    variants: [
      { label: "250ml", price: 4.0 },
      { label: "1.5lt", price: 35.0 },
      { label: "5lt", price: 80.0 },
    ],
    ingredients: "Hibiscus petals, water, ginger, cloves, natural sweetener.",
    nutritionInfo: "Calories: 45 per 250ml, Rich in Vitamin C",
    shelfLife: "3 days (refrigerated)",
    allergens: "None",
    storage: "Keep refrigerated. Shake well before serving.",
    reviews: [],
  },
  {
    id: "PRD-JS008",
    title: "Pineapple Juice",
    description: "Freshly pressed pineapple, sweetened with honey and finished with a hint of cloves. No artificial flavors or preservatives — just pure, wholesome goodness in every sip. Available in 250ml square bottle, 1.5lt, and 5lt gallon.",
    price: 5.0,
    category: "Drinks",
    rating: 4.7,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.img1],
    weight: "250ml",
    variants: [
      { label: "250ml", price: 5.0 },
      { label: "1.5lt", price: 50.0 },
      { label: "5lt", price: 95.0 },
    ],
    ingredients: "Fresh pineapple, honey, cloves.",
    nutritionInfo: "Calories: 60 per 250ml, Vitamin C: 25mg",
    shelfLife: "3 days (refrigerated)",
    allergens: "None",
    storage: "Keep refrigerated. Shake well before serving.",
    reviews: [],
  },
  {
    id: "PRD-JS009",
    title: "Gingerpine Juice",
    description: "A bold fusion of pineapple, ginger, honey, cinnamon, and cloves. Warming, zesty, and deeply flavorful — a great digestive aid and natural energy booster. Available in 250ml square bottle, 1.5lt, and 5lt gallon.",
    price: 6.0,
    category: "Drinks",
    rating: 4.8,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.img1],
    weight: "250ml",
    variants: [
      { label: "250ml", price: 6.0 },
      { label: "1.5lt", price: 55.0 },
      { label: "5lt", price: 105.0 },
    ],
    ingredients: "Fresh pineapple, fresh ginger, honey, cinnamon, cloves.",
    nutritionInfo: "Calories: 55 per 250ml, Anti-inflammatory",
    shelfLife: "3 days (refrigerated)",
    allergens: "None",
    storage: "Keep refrigerated. Shake well before serving.",
    reviews: [],
  },
  {
    id: "PRD-JS010",
    title: "Gingermelon Juice",
    description: "A refreshing blend of watermelon, ginger, honey, and cinnamon. The natural sweetness of watermelon balances the warming spices perfectly, making this a deeply hydrating and revitalizing drink for warm days on campus. Available in 250ml square bottle, 1.5lt, and 5lt gallon.",
    price: 8.0,
    category: "Drinks",
    rating: 4.6,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.img1],
    weight: "250ml",
    variants: [
      { label: "250ml", price: 8.0 },
      { label: "1.5lt", price: 60.0 },
      { label: "5lt", price: 125.0 },
    ],
    ingredients: "Watermelon, fresh ginger, honey, cinnamon.",
    nutritionInfo: "Calories: 50 per 250ml, Hydrating",
    shelfLife: "3 days (refrigerated)",
    allergens: "None",
    storage: "Keep refrigerated. Shake well before serving.",
    reviews: [],
  },
  {
    id: "PRD-JS011",
    title: "Sweetgreen Juice",
    description: "A light and refreshing blend of pineapple, cucumber, and mint, sweetened naturally with honey. Clean, hydrating, and energizing — the perfect healthy companion to your Joy Snacky meal. Available in 250ml square bottle, 1.5lt, and 5lt gallon.",
    price: 8.0,
    category: "Drinks",
    rating: 4.5,
    availability: true,
    state: "Freshly Made",
    type: "Product",
    images: [images.img1],
    weight: "250ml",
    variants: [
      { label: "250ml", price: 8.0 },
      { label: "1.5lt", price: 60.0 },
      { label: "5lt", price: 125.0 },
    ],
    ingredients: "Fresh pineapple, cucumber, mint, honey.",
    nutritionInfo: "Calories: 40 per 250ml, Rich in vitamins",
    shelfLife: "2 days (refrigerated)",
    allergens: "None",
    storage: "Keep refrigerated. Shake well before serving.",
    reviews: [],
  },
  {
    id: "PRD-JS012",
    title: "Cocobeet Juice",
    description: "A nutrient-dense power blend of coconut, beetroot, ginger, tigernut, dates, and honey. Rich in natural energy, antioxidants, and minerals — this thick, earthy-sweet juice is one of our most wholesome offerings. Available in 250ml square bottle and 1.5lt.",
    price: 0.0,
    category: "Drinks",
    rating: 0,
    availability: false,
    state: "Coming Soon",
    type: "Product",
    images: [images.img1],
    weight: "250ml",
    variants: [
      { label: "250ml", price: 0.0 },
      { label: "1.5lt", price: 0.0 },
    ],
    ingredients: "Coconut, beetroot, fresh ginger, tigernut, dates, honey.",
    nutritionInfo: "High in iron, natural energy boost",
    shelfLife: "2 days (refrigerated)",
    allergens: "Contains Tree Nuts (Coconut, Tigernut).",
    storage: "Keep refrigerated. Shake well before serving.",
    reviews: [],
  },
];

const useProductStore = create(
  persist(
    (set, get) => ({
      products: initialProducts,
      addProduct: (product) =>
        set((state) => ({ products: [...state.products, product] })),
      updateProduct: (updatedProduct) =>
        set((state) => ({
          products: state.products.map((p) =>
            p.id === updatedProduct.id ? updatedProduct : p
          ),
        })),
      deleteProduct: (id) =>
        set((state) => ({
          products: state.products.filter((p) => p.id !== id),
        })),
      getProductById: (id) => get().products.find((p) => p.id === id),
    }),
    { name: "vendor-products", version: 1 }
  )
);

export default useProductStore;
